"""
Medical Disease Prediction — XGBoost Training Pipeline
Auto-generated by medical_pipeline.py
"""

import pandas as pd
import numpy as np
import json
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report, confusion_matrix
import xgboost as xgb
import shap
import matplotlib.pyplot as plt
import seaborn as sns

# ── Load Data ──────────────────────────────────────────────────────────────

train = pd.read_csv("output/train.csv")
test  = pd.read_csv("output/test.csv")

with open("output/feature_dictionary.json") as f:
    feat_dict = json.load(f)
with open("output/label_encoder.json") as f:
    enc_map = json.load(f)

# ── Encode Categoricals ────────────────────────────────────────────────────

CAT_COLS = ["age_group", "sex", "bmi_group", "sleep_quality",
            "stress_level", "employment_status", "season", "region",
            "onset_speed", "row_type"]

oe = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)
train[CAT_COLS] = oe.fit_transform(train[CAT_COLS].astype(str))
test[CAT_COLS]  = oe.transform(test[CAT_COLS].astype(str))

# ── Target Encoding ────────────────────────────────────────────────────────

le = LabelEncoder()
y_train = le.fit_transform(train["label"])
y_test  = le.transform(test["label"])

DROP_COLS = ["label", "row_type", "is_emergency", "psychosis_present",
             "self_harm_risk", "needs_specialist"]
FEATURE_COLS = [c for c in train.columns if c not in DROP_COLS]

X_train = train[FEATURE_COLS].fillna(0)
X_test  = test[FEATURE_COLS].fillna(0)

print(f"Train: {X_train.shape}, Test: {X_test.shape}")
print(f"Classes: {len(le.classes_)}")

# ── XGBoost Model ─────────────────────────────────────────────────────────

model = xgb.XGBClassifier(
    n_estimators=400,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    use_label_encoder=False,
    eval_metric="mlogloss",
    n_jobs=-1,
    random_state=42,
    tree_method="hist",
)

model.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],
    verbose=50,
)

# ── Evaluation ────────────────────────────────────────────────────────────

y_pred = model.predict(X_test)
print("\n=== Classification Report ===")
print(classification_report(y_test, y_pred, target_names=le.classes_))

# Confusion matrix (top-20 classes by frequency)
cm = confusion_matrix(y_test, y_pred)
top_classes = pd.Series(y_test).value_counts().head(20).index.tolist()
cm_sub = cm[np.ix_(top_classes, top_classes)]
fig, ax = plt.subplots(figsize=(16, 14))
sns.heatmap(cm_sub, xticklabels=le.classes_[top_classes],
            yticklabels=le.classes_[top_classes],
            annot=True, fmt="d", cmap="Blues", ax=ax)
plt.title("Confusion Matrix (Top 20 Diseases)")
plt.tight_layout()
plt.savefig("output/confusion_matrix.png", dpi=150)
print("Saved confusion_matrix.png")

# ── Feature Importance ────────────────────────────────────────────────────

importances = pd.Series(model.feature_importances_, index=FEATURE_COLS)
top_features = importances.nlargest(30)
fig, ax = plt.subplots(figsize=(10, 8))
top_features.sort_values().plot.barh(ax=ax)
ax.set_title("Top 30 Feature Importances")
plt.tight_layout()
plt.savefig("output/feature_importance.png", dpi=150)
print("Saved feature_importance.png")

# ── SHAP Explainability ───────────────────────────────────────────────────

explainer = shap.TreeExplainer(model)
shap_sample = X_test.sample(min(500, len(X_test)), random_state=42)
shap_values = explainer.shap_values(shap_sample)

shap.summary_plot(shap_values, shap_sample, show=False,
                  max_display=25, plot_type="bar")
plt.title("SHAP Feature Importance (mean |SHAP|)")
plt.tight_layout()
plt.savefig("output/shap_summary.png", dpi=150, bbox_inches="tight")
print("Saved shap_summary.png")

model.save_model("output/medical_model.xgb")
print("\nModel saved to output/medical_model.xgb")
